### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Arshad4617** [sanjaykuppan/supernova#1]
Traceback (most recent call last):
  File "/media/user/abc/PROG/supernova/sntest1.py", line 93, in <module>
    MainWindow()
  File "/media/user/abc/PROG/supernova/sntest1.py", line 58, in MainWindow
    box.state('zoomed')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2211, in wm_state
    return self.tk.call('wm', 'state', self._w, newstate)
_tkinter.TclError: bad argument "zoomed": must be normal, iconic, or withdrawn

**Comment by sanjaykuppan** [comment]
seems to be an issue only on linux platform, works good on windows, will check on this issue
